Base:
    window_size: 45
    batch_size: 64
    compared_length: null
    penalty: null
    negative_penalty: 1
    nb_steps: 500
    lr: 0.001
    nb_random_samples: 5

casualCnn:
    channels: 40
    depth: 2
    in_channels: 1 # 输入有几维度KPI
    kernel_size: 3 # 同时考虑多少个token
    out_channels: 64
    reduced_size: 32
    embedding_dim: 10
