Base:
    window_size: 45
    batch_size: 64
    compared_length: null
    penalty: null
    negative_penalty: 1
    nb_steps: 50
    lr: 0.001
    nb_random_samples: 5

casualCnn:
    channels: 40
    depth: 10
    in_channels: 1 # 输入有几维度KPI
    kernel_size: 3 # 同时考虑多少个词
    out_channels: 300
    reduced_size: 160
    embedding_dim: 10
