Base:
    window_size: 20
    batch_size: 64
    compared_length: null
    penalty: null
    negative_penalty: 1
    nb_steps: 2000
    lr: 0.001
    nb_random_samples: 5
    nb_steps_per_verbose: 2000

casualCnn:
    channels: 40
    depth: 2
    in_channels: 1 # 输入有几维度KPI
    kernel_size: 3 # 同时考虑多少个token
    out_channels: 64
    reduced_size: 32
    discretized: False

mlstm:
    hidden_size: 64
    num_layers: 2
    discretized: False
    normalize: minmax # minmax, standard, robust
